# Generated by Django 3.2.13 on 2022-07-05 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('prob_id', models.IntegerField(primary_key=True, serialize=False)),
                ('topic', models.CharField(choices=[('Arrays', 'Array'), ('Matrices', 'Matrices'), ('Searching', 'Searching'), ('Sorting', 'Sorting'), ('Hashing', 'Hashing'), ('LinkedList', 'LinkedList'), ('Stacks', 'Stacks'), ('Queues', 'Queues'), ('Trees', 'Trees'), ('Graphs', 'Graphs'), ('Greedy', 'Greedy'), ('D&C', 'Divide&Conquer'), ('DP', 'Dynamic Programming')], max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('level', models.IntegerField(choices=[(1, 'Easy'), (2, 'Moderate'), (3, 'Hard')], default=1)),
                ('crr_sub', models.IntegerField()),
                ('total_sub', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Submission_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('lang', models.CharField(choices=[('cpp', 'C++'), ('python', 'python')], max_length=6)),
                ('verdict', models.CharField(choices=[('RTE', 'RunTimeError'), ('CE', 'CompilationError'), ('Success', 'Success')], max_length=7)),
                ('sub_time', models.DateTimeField(auto_now_add=True)),
                ('prob_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.problem')),
            ],
        ),
        migrations.CreateModel(
            name='Test_Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.TextField()),
                ('output', models.TextField()),
                ('prob_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.problem')),
            ],
        ),
        migrations.CreateModel(
            name='User_Data',
            fields=[
                ('user_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('subs', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='submission_log',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.user_data'),
        ),
    ]
